### ISSUE TITLE
how to crawl sites which are in different languages

### ISSUE THREAD

**Issue by deepika537** [salimk/Rcrawler#13]
I want to crawl "https://www.vebeg.de/web/en/verkauf/suchen.htm?DO_SUCHE=1&SUCH_MATGRUPPE=1300" website. This website has content in german language. 

Also, How to overwrite/add the content to folder created with domain name. I am unable to crawl 2 different pages of same website at a time because it is giving me warning saying that folder already exists when I start crawling the different page of the same website.
Forexample
1. Rcrawler(Website ="https://www.proxibid.com/asp/SearchAdvanced_i.asp?searchTerm=aviation&category=all+categories#search", no_cores = 10, no_conn = 10,MaxDepth=1,Encod="UTF-8")
2. Rcrawler(Website ="https://www.proxibid.com/asp/AuctionsByCompany.asp?ahid=743", no_cores = 10, no_conn = 10,MaxDepth=1,Encod="UTF-8")

First command downloaded pages successfully. Second command is not downloading any pages.

**Comment by salimk** [comment]
1- The first website requires a ISO-8859-1 encoding, which was not provided in the http header, so improved our detection encoding process to overcome this situation, now it can be crawled smoothly.
![image](https://user-images.githubusercontent.com/17308124/31966716-7c4d4398-b903-11e7-9de7-5d643424aa3b.png)
2- The second issue is related to content folder remain the same so it's overridden on each operation, to resolve this issue we have added an identifier (random number)  to the directory name to be different in each crawling operation.  

3-   After checking this https://www.proxibid.com/asp/AuctionsByCompany.asp?ahid=743 it's a server latency problem you shoud set  Timeout to value superior to 7 then it works .However, you must Always use less than 4 no_cores and 4 no_conn, to avoid being suspended by the server firewall or security software. many concurrent requests are against their policy because it's not human and overloads their web servers. 
`> Rcrawler(Website ="https://www.proxibid.com/asp/AuctionsByCompany.asp?ahid=743", no_cores = 2, no_conn = 2,MaxDepth=1,Encod="UTF-8", Timeout = 7)`
In process : 1..
Progress: 1.18 %  :  1  parssed from  85  | Collected pages: 1  | Level: 1 
In process : 2..3..
Progress: 2.30 %  :  2  parssed from  87  | Collected pages: 3  | Level: 1 
In process : 4..5..
Progress: 1.87 %  :  4  parssed from  214  | Collected pages: 5  | Level: 1

**Comment by deepika537** [comment]
Thank you for your quick reply. When are you going to release your new version?
