### ISSUE TITLE
Too slow with keywordfilter option

### ISSUE THREAD

**Issue by deepika537** [salimk/Rcrawler#15]
How can I download pages faster by specifying KeywordsFilter value in Rcrawler()
**For example**
Rcrawler(Website ="http://www.salvex.com/listings/index.cfm?catID=1280&regID=0&mmID=0&orderBy=1&order=0&filterWithin=&f",Timeout=7,Encod=Getencoding("http://www.salvex.com/listings/index.cfm?catID=1280&regID=0&mmID=0&orderBy=1&order=0&filterWithin=&f"),no_cores = 2,  KeywordsFilter = c("A250","aeroplane","AH-1" ,"AH-64" ,"aircraft","airframe","airplane","Allison","AS365 Dauphin","auction","aviation","Aviation Fueling Directory","Aviation Museums","Avionics","Bell 205 ","Bell 206 ","Bell 212","Bell 214","Bell 412","blades","Blades","Boeing","C20B","CH-47","CH-47 ","CH-53 ","Chinook","Cobra","driveshaft","engine","Eurocopter AS350","FLIR unit","fuel cell","Fuel Control","fuselage","gearbox","Ground Support Equipment (GSE)","Helicopter","hub assembly","Huey","Hughs","J85 ","Jet Ranger","JT8 ","JT9 ","Kamon","Kiowa","Long Ranger","LTS101 ","Lycoming","M250","main rotor blades","MR Blade","main rotor hub","MR Hub","MD500 ","OH-58","OH-58","OH-6","Pratt and Whitney","PT-6","PT6","Rolls Royce","servos","Sikorsky","skids","surplus","swashplate assembly","T53","T53-L-13B","T53-L-703","T55","T56 ","T58","T63","T63 ","T700 ","tail rotor blades","TR Blades","tail rotor hub","TR Hub","tailboom","transmission","turbine","Turboprop","UH1","UH-1","UH-1H","UH-60","UH60 ","vertical stabilizer","wire strike kit"),no_conn = 2,MaxDepth=1)

**Comment by salimk** [comment]
I have done some tunings to keywords filter function ,then i have run the same command on my computer with system.time(), and the crawling speed was normal except for some pages it takes up to 10 sec, then it continues normally because the page is big ( http://www.salvex.com/listings/index.cfm. ) In fact for each page the function looks for every keyword and count its occurrences .

![captureeee](https://user-images.githubusercontent.com/17308124/32419935-9f8b3f56-c27a-11e7-8746-0fa6fe3947c4.PNG)

Thanks,
